@base_url = http://localhost:8080

### Try Creating User Without a Name
POST {{base_url}}/users
Content-Type: application/json

{
  "surname": "Doe",
  "email": "noname@gmail.com",
  "password": "password"
}

> {%
    client.test("Missing name validation error", function () {
        client.assert(response.status == 400)
    });
%}
